name: Publish Log4brains
on:
  push:
    branches:
      - master
      - dev # debug. TODO: remove
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Install and Build Log4brains
        run: |
          echo ${{ github.repository.name }}
          yarn install --frozen-lockfile
          yarn build
          yarn links
          yarn log4brains-build --basePath /${{ github.repository.name }}/adr
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .log4brains/out
          TARGET_FOLDER: adr
